In [2]:
import numpy as np

In [3]:
myList=[1,2,3]
myList

[1, 2, 3]

In [4]:
np.array(myList)

array([1, 2, 3])

In [5]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [6]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [19]:
# broadcasting
arr[2:9]=100
arr

array([  0,   1, 100, 100, 100, 100, 100, 100, 100,   9,  10])

In [21]:
# Selecting data from numpy array
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
# data ele>2
selected=dice_rolls[dice_rolls>2];
size=selected.size
size

19

In [30]:
# numpy operations

arr=np.arange(0,10)

# 1/arr
# np.sqrt(arr)
# np.sin(arr)
# np.log(arr)
# arr.sum()
# arr.mean()
# arr.std()
# arr.max()
arr.var()

8.25

In [38]:
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr2d.shape

(5, 5)

In [40]:
arr2d.sum()

300

In [42]:
# axis=0 row wise
# axis=1 column wise

arr2d.sum(axis=0)
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [45]:
# find total
arrList=[100,-200,300,-400,100,100,-230,450,500,2000]
account_transactions = np.array(arrList)
total=account_transactions.sum();
total

2720

In [54]:
# Numpy Exersise

np.zeros(10)
arr=np.ones(10)
arr[:]=5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [55]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [56]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [57]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.random.rand()
np.random.rand(3)
np.random.rand(3,5)

array([[0.58548468, 0.34735645, 0.03201616, 0.63182709, 0.22434541,
        0.33499505, 0.37656271, 0.81463231, 0.96392419, 0.16504992],
       [0.05588312, 0.11454324, 0.08448429, 0.40586116, 0.60366482,
        0.87510218, 0.38019645, 0.29055674, 0.47540091, 0.25700603],
       [0.59962868, 0.79394749, 0.22045698, 0.25958875, 0.90565021,
        0.22336027, 0.47635729, 0.15247683, 0.16567785, 0.83832537],
       [0.21363646, 0.20728938, 0.12435852, 0.46944018, 0.28659533,
        0.80783926, 0.49564157, 0.61107445, 0.7781541 , 0.02293242],
       [0.64523333, 0.66068041, 0.1790619 , 0.28043401, 0.15977723,
        0.08023872, 0.73556384, 0.21699414, 0.00243463, 0.55708371],
       [0.70481051, 0.56542096, 0.90293218, 0.33050876, 0.14445579,
        0.55604408, 0.54427339, 0.28931685, 0.46936962, 0.28484588],
       [0.24801109, 0.15045524, 0.91073472, 0.83876677, 0.57563371,
        0.65796696, 0.24763154, 0.965633  , 0.79996116, 0.71459674],
       [0.83528679, 0.4868845 , 0.4791176

In [77]:
np.random.randint(90)
np.random.randint(100,size=(3))
np.random.randint(100,size=(3,5))


array([[13, 76, 35, 68, 46],
       [21, 23, 22, 63,  0],
       [12, 69, 54, 64, 26]])

In [93]:
np.random.standard_normal()
np.random.standard_normal(25)
np.random.standard_normal(size=(3,5))

TypeError: standard_normal() takes at most 1 positional argument (2 given)

In [98]:
np.linspace(0.01,1,num=100).round(2).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [100]:
np.linspace(0,1,num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Numpy Indexing and Selection

In [102]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [109]:
mat[2:,2:]
mat[3,4]
mat[0:3,1:2]
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
# Operations
mat.sum()
mat.sum(axis=1)
# mat.mean()

array([ 15,  40,  65,  90, 115])

In [112]:
mat.var()
mat.std()

7.211102550927978